services:
  db:
    image: postgres:16
    container_name: poe_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: poe_uniques
      POSTGRES_USER: poe
      POSTGRES_PASSWORD: poe
    ports:
    - "5433:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: